### ISSUE TITLE
Unnresolved dependancies

### ISSUE THREAD

**Issue by pkvpraveen** [dsosnoski/concur1#1]
I tried to clone theproject. But classes DistancePair and TimingTestBase in Java are not present.

Thank you for sharing the example.

**Comment by dsosnoski** [comment]
The classes are from the Scala code, the Java code uses them directly.

Glad you're finding it useful!
- Dennis

**Comment by pkvpraveen** [comment]
Thank you for quick response. Closing the issue.

**Comment by Kikou1984** [comment]
Can we have these classes in java language please. I don t  know Scala. 

Thank you
